create table if not exists public.scorms_users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  pass text null,
  admin boolean null,
  alertador boolean null,
  agente text null,
  constraint scorms_users_pkey primary key (id)
) TABLESPACE pg_default;
