create table if not exists public.scorms_etiquetas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  etiqueta_codigo text null,
  etiqueta_nombre text null,
  clasificacion_scorm text null,
  constraint scorms_etiquetas_pkey primary key (id)
) tablespace pg_default;

alter table public.scorms_master
add column if not exists scorms_alerta timestamp with time zone null;

create or replace view public.alertas_actualizaciones as
select
  sm.*,
  sm.scorms_alerta as alerta_actualizacion_fecha
from public.scorms_master sm
where sm.scorms_alerta is not null;
