create table if not exists public.scorms_cursos_actualizaciones (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "IDUnico" text null,
  usuario text null,
  scorms_anadidos text null,
  scorms_eliminados text null,
  constraint scorms_cursos_actualizaciones_pkey primary key (id)
) TABLESPACE pg_default;

alter table if exists public.scorms_cursos_actualizaciones
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists "IDUnico" text null,
  add column if not exists usuario text null,
  add column if not exists scorms_anadidos text null,
  add column if not exists scorms_eliminados text null;

create index if not exists idx_scorms_cursos_actualizaciones_idunico
  on public.scorms_cursos_actualizaciones ("IDUnico");

create index if not exists idx_scorms_cursos_actualizaciones_created_at
  on public.scorms_cursos_actualizaciones (created_at desc);
