create table if not exists public.scorms_alertas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  scorm_codigo text null,
  alerta_fecha timestamp with time zone null,
  alerta_novedad text null,
  alerta_etiquetas text null,
  constraint scorms_alertas_pkey primary key (id)
) tablespace pg_default;
