-- Tabla para consolidar el histórico de actualizaciones de SCORM.
CREATE TABLE IF NOT EXISTS public.scorms_actualizacion (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  fecha_modif timestamp without time zone,
  scorm_codigo text,
  cambio_tipo text,
  cambio_user text,
  cambio_notas text,
  CONSTRAINT scorms_actualizacion_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;
